#!/bin/bash

# Set date and latest tag for builds on master branch
if [ "$SOURCE_BRANCH" = "master" ]
then
    # latest tag is deployed using gh actions
    # docker tag $DOCKER_REPO $DOCKER_REPO:latest
    docker tag $DOCKER_REPO $DOCKER_REPO:"$(date '+%Y_%m_%d')"
fi

# Dev branch is deployed using gh actions
# Set branch tag for builds on dev branch
# if [ "$SOURCE_BRANCH" = "dev" ]
# then
#     docker tag $DOCKER_REPO $DOCKER_REPO:$SOURCE_BRANCH
# fi