#!/bin/bash

# Push date tag for builds on master branch
if [ "$SOURCE_BRANCH" = "master" ]
then
    docker push $DOCKER_REPO:"master_$(date '+%Y_%m_%d')"
fi

# Push branch tag
docker push $DOCKER_REPO:$SOURCE_BRANCH
