name: Build and Deploy Dev

on:
  push:
    branches:
      - 'dev'

env:
  IMAGE_NAME: devenv

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set environmen variables
        run: |
          echo "Datetag=$(date +'%Y-%m-%d')_dev" >> $GITHUB_ENV
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          echo "IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            ghcr.io/${{ env.IMAGE_ID }}:${{ env.Datetag }}, 
            ghcr.io/${{ env.IMAGE_ID }}:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
