name: Deploy Master DH

on:
  push:
    # Publish `master` as Docker `lastest` and $DATE image.
    branches:
      - master

jobs:

  # Push image to Dockerhub
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Currently unused, shall be used in the future
      - name: Set current date
        run:  
          echo "::set-env name=DATE::$(date +'%Y-%m-%d')"

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: berrij/devenv
          tags: latest